POST http://localhost:7071/api/SendEchoRequest HTTP/1.1
Accept: application/json

{
    "id": "1234",
    "name": "John Doe",
    "email": "
}

###
POST http://localhost:7071/api/SendEchoRequest HTTP/1.1
Accept: application/json


###
GET http://localhost:7071/api/SendEchoRequest?parameterXYZ=1&parameterXYZ=2 HTTP/1.1
Accept: application/json


###
GET http://localhost:7071/api/SendEchoRequest HTTP/1.1
Accept: application/json

