POST http://localhost:7071/api/Echo HTTP/1.1
Accept: application/json

{
    "id": "1234",
    "name": "John Doe",
    "email": "
}

###

GET http://localhost:7071/api/Echo?parameterXYZ=1&parameterXYZ=2 HTTP/1.1
Accept: application/json
